New Development Section
PJ-ODS-2021/P2P-Task pull request #12
Opened 2021-06-16 06:48 UTC by firstdayofjune

- described the workflow, CI pipeline and directory structure
- added tips & tricks (flutter format file watcher)

OPTM-24 #close

2021-06-16 14:48 UTC, PitchBlackCoffee commented
I propose some minor changes/fixes:

````diff
diff --git a/README.md b/README.md
index 90261fc..dd25440 100644
--- a/README.md
+++ b/README.md
@@ -1,12 +1,12 @@
 # P2P Task Manager
 
-A privacy-aware task manager. No account needed, all your tasks get synced using the local network only. 
+A privacy-aware task manager. No account needed, all your tasks get synced using the local network only.
 
 ## Getting Started
 
-Follow the instruction on https://flutter.dev/docs/get-started/install
+Follow the instruction on <https://flutter.dev/docs/get-started/install>
 
-Follow the instructions on https://flutter.dev/docs/get-started/editor
+Follow the instructions on <https://flutter.dev/docs/get-started/editor>
 
 Run `flutter pub get` in the terminal to load all dependencies
 
@@ -22,14 +22,14 @@ A few resources to get you started:
 - [Cookbook: Useful Flutter samples](https://flutter.dev/docs/cookbook)
 - [Online Documentation](https://flutter.dev/docs)
 
-# Development
+## Development
 
 Read this section, if you want to contribute to the project.
 
 ## Workflow
 
 1. Select a JIRA issue to work on.
-2. Create a feature branch for the issue, named _OPTM-XY_Meaninful-Branch-Name_)
+2. Create a feature branch for the issue, named _OPTM-XY_Meaningful-Branch-Name_)
 3. Write your code and add tests for it
 4. Format your files (`flutter run format <filenames>` or `dart run format <filenames>`)
 5. Run all tests (`flutter test`) and make sure they complete without errors or warnings
@@ -44,6 +44,7 @@ Every file gets checked for proper formatting. Also, all tests get executed.
 You can find all the commands run on CI in `.github/workflows/main.yaml`.
 
 ## Directory Structure
+
 ```
 root
 // Contains the application code
@@ -82,6 +83,6 @@ In Visual Studio Code:
 > Install the Flutter extension (see [Editor setup](https://flutter.dev/docs/get-started/editor)) to get automatic formatting of code in VS Code.
 >
 > To automatically format the code in the current source code window, right-click in the code window and
-select Format Document. You can add a keyboard shortcut to this VS Code Preferences.
+> select Format Document. You can add a keyboard shortcut to this VS Code Preferences.
 >
 > To automatically format code whenever you save a file, set the _editor.formatOnSave_ setting to true.
````

2021-06-17 07:54 UTC, JacobRoe requested changes
Beside the proposed changes by Konstantin, you might, in case you incorporate Konstantin's suggestions, want to adjust the child headers for the `Development` sections too.

I'm also not quite sure why we should use less then and greater than symbols for denoting a link. Typically, it gets rendered in blue anyway. Opinions? (Referring to Konstantin suggested changes.)

2021-06-17 08:34 UTC, PitchBlackCoffee commented
> I'm also not quite sure why we should use less then and greater than symbols for denoting a link. Typically, it gets rendered in blue anyway. Opinions? (Referring to Konstantin suggested changes.)

https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md034

2021-06-17 08:52 UTC, JacobRoe commented
> > I'm also not quite sure why we should use less then and greater than symbols for denoting a link. Typically, it gets rendered in blue anyway. Opinions? (Referring to Konstantin suggested changes.)
> 
> https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md034

Thank you. It also states the rationale at the end: "Without angle brackets, the URL isn't converted into a link by many markdown parsers." To be honest, it never happened to me that it didn't get correctly rendered (and I use markdown extensively). But at least now I see why it can make sense to add them. So, no objections anymore from my side.

2021-06-29 10:35 UTC, firstdayofjune commented
I included the proposed changes and the README to reflect the new metrics in CI.

2021-06-29 13:13 UTC, PitchBlackCoffee requested changes

2021-06-29 13:13 UTC, guisedlythe commented on README.md
> +- Files are formatted using `flutter format`
Maybe a bit misleading: the CI checks if the files you committed are properly formatted, it doesn't actually format the files files for you.

2021-06-29 13:13 UTC, guisedlythe commented on README.md
> +- Run `git submodule init && git submodule update` (this project uses the lww_crdt library as a submodule)
Insert empty line before list: https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md032

2021-06-29 13:13 UTC, PitchBlackCoffee commented on README.md
>  ```
Insert empty line after heading: https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md022

2021-06-29 13:13 UTC, PitchBlackCoffee commented on README.md
> +    flutter pub run dart_code_metrics:metrics lib
Use consistent block style: https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md046
E.g.:
````
```sh
flutter pub run dart_code_metrics:metrics lib
```
````

2021-06-29 13:13 UTC, PitchBlackCoffee commented on README.md
> +6. Run code metrics (`flutter pub run dart_code_metrics:metrics lib`) and fix warnings related to your changes
Maybe just add a reference to the 'Run code metrics locally section'.
E.g.:
```md
[Run code metrics](#run-code-metrics-locally)
```

2021-06-29 13:13 UTC, PitchBlackCoffee commented on README.md
> +Run the following command to get information about the code metrics
Maybe add that the following command runs the metrics only in the `lib` folder, use `flutter pub run dart_code_metrics:metrics lib test` to run it in the `test` folder as well.

2021-07-02 18:04 UTC, PitchBlackCoffee approved these changes
Approved, except the minor changes that I already pushed to this branch.

2021-07-07 14:19 UTC, JacobRoe approved these changes

2021-07-07 14:19 UTC, merged