OPTM-63 Only show QR scanner button when platform is web, android, iOS.
PJ-ODS-2021/P2P-Task pull request #18
Opened 2021-06-25 18:30 UTC by PitchBlackCoffee

- When QR scanner is not supported for the platform, only allow adding devices with the "device form screen"

OPTM-63 #close

2021-06-25 18:30 UTC, PitchBlackCoffee commented
I think I forgot to create a PR for this (minor) change

2021-06-27 07:08 UTC, JacobRoe requested changes
LGTM except the things I commented on.

2021-06-27 07:08 UTC, JacobRoe commented on lib/screens/devices/device_list_screen.dart
> +    final consumerWidget = Consumer2<PeerInfoService, PeerService>(
Shouldn't it be `ChangeCallbackNotifier<PeerInfoService>` and `ChangeCallbackNotifier<PeerService>`?

2021-06-27 07:08 UTC, JacobRoe commented on lib/screens/devices/device_list_screen.dart
> +                    : Text('Press the button below to add a device'),
Maybe add a period to the sentence to keep it consistent.

2021-06-28 08:00 UTC, JacobRoe approved these changes
Thank you. Looks good.

2021-06-28 08:00 UTC, merged