Add badges to README.md
PJ-ODS-2021/P2P-Task pull request #28
Opened 2021-07-07 19:26 UTC by JacobRoe

OPTM-90

2021-07-08 13:38 UTC, PitchBlackCoffee requested changes
We should also add the license to this and and the lww_crdt repository via github (if we choose this license and have checked if we are allowed to apply it with the libraries that we use).

2021-07-08 13:39 UTC, PitchBlackCoffee requested changes

2021-07-08 13:39 UTC, PitchBlackCoffee commented on README.md
> +![CI](https://github.com/PJ-ODS-2021/P2P-Task/actions/workflows/main.yaml/badge.svg)
Please add a newline after the section header:
https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md022

2021-07-09 08:18 UTC, firstdayofjune approved these changes

2021-07-09 08:20 UTC, firstdayofjune commented
Thanks for your changes. I will check the license compatibility and also look for a way to display the used packages in the settings section.

2021-07-09 08:20 UTC, firstdayofjune submitted a review, later dismissed

2021-07-09 13:15 UTC, PitchBlackCoffee approved these changes, later dismissed

2021-07-10 10:53 UTC, firstdayofjune commented
I added the GPL-v3 license to the project, which makes the app truly free software.
I therefore added everyone as a reviewer to confirm the choice of license.
Refer to https://choosealicense.com/licenses/gpl-3.0/ or https://www.gnu.org/licenses/quick-guide-gplv3.html for more info on the GPL.

2021-07-10 10:55 UTC, firstdayofjune submitted a review, later dismissed

2021-07-10 16:30 UTC, Tan-jay approved these changes, later dismissed

2021-07-10 17:59 UTC, PitchBlackCoffee approved these changes, later dismissed

2021-07-13 16:56 UTC, bithianjuman submitted a review, later dismissed

2021-07-14 08:51 UTC, firstdayofjune approved these changes

2021-07-14 08:51 UTC, merged