OPTM-48 add description
PJ-ODS-2021/P2P-Task pull request #6
Opened 2021-06-02 09:58 UTC by Tan-jay

2021-06-04 14:20 UTC, JacobRoe requested changes
Nice, very good!

You might want to address my comments. Mandatory for an approval would be the part about reusing the previous provider in _onSubmitPressed. Otherwise, it's on point.

2021-06-04 14:20 UTC, JacobRoe commented on lib/screens/task_form_screen.dart
> +          .upsert(_task..description = _formDescriptionController.text);
You could reuse the previous provided service + use the cascade operator (..) of Dart like e.g.:
```dart
final taskListService = Provider.of<TaskListService>(context, listen: false);
taskListService.upsert(_task
    ..title = _formController.text
    ..description = _formDescriptionController);
```

* https://dart.dev/guides/language/language-tour#cascade-notation

2021-06-04 14:20 UTC, JacobRoe commented on lib/screens/task_list_screen.dart
> +        subtitle: Text(description),
You could use the syntactic sugar of Dart like e.g.
```dart
subtitle: Text(task.description ?? ''),
```

* https://dart.dev/guides/language/language-tour#conditional-expressions

2021-06-07 17:56 UTC, Tan-jay commented
> Nice, very good!
> 
> You might want to address my comments. Mandatory for an approval would be the part about reusing the previous provider in _onSubmitPressed. Otherwise, it's on point.

done, thanks! :)

2021-06-11 10:44 UTC, JacobRoe commented
> > Nice, very good!
> > You might want to address my comments. Mandatory for an approval would be the part about reusing the previous provider in _onSubmitPressed. Otherwise, it's on point.
> 
> done, thanks! :)

Looks very good, thank you!

2021-06-11 10:44 UTC, merged